[package]
name = "deathrip"
authors = ["Yehuthith <yehuthit@gmail.com>"]
description = "Rips full-resolution images from the Dead Sea Scrolls digital library."
version = "0.1.1"
edition = "2021"
repository = "https://github.com/yehuthi/deathrip"
keywords = ["history", "judaism", "israel", "bible", "literature"]
categories = ["command-line-utilities", "multimedia::images"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
const_format = "0.2.24"
futures = "0.3.21"
image = "0.24.2"
itertools = "0.10.3"
itoa = "1.0.2"
regex = "1.5.6"
reqwest = "0.11.10"
tokio = { version = "1.19.2", features = ["rt", "macros"] }
