[package]
name = "deathrip"
authors = ["Yehuthith <yehuthit@gmail.com>"]
description = "Rips full-resolution images from the Dead Sea Scrolls digital library."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/yehuthi/deathrip"
keywords = ["history", "judaism", "israel", "bible", "literature"]
categories = ["command-line-utilities", "multimedia::images"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = "2.33"
futures = "0.3"
image = "0.23"
itertools = "0.10"
itoa = "0.4"
regex = "1.5"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
